Stream product collection part3
BulavaKatsyaryna/JiS7 pull request #35
Opened 2021-05-28 12:19 UTC by BulavaKatsyaryna

2021-05-28 12:36 UTC, KaydunovDenis requested changes
See my comments

2021-05-28 12:36 UTC, KaydunovDenis commented on src/main/java/LECTURE_Stream_API_And_Lambdas/Task3_Product3/Demo.java
> +        List<Product> minPriceInTheCollectionWithTheMaxDiscount = listProduct.stream()
Мой английский не так хорошо как хотелось бы но думаю в названии метода писать The необязательно

Посмотри как я решил эту задачку:
```
productRepository.getListProducts().stream()                
     .min(Comparator.comparing(Product::getPrice)                                  
     .thenComparing((o1, o2) ->
            Double.compare(o2.getDiscount(), o1.getDiscount()))) 
      .ifPresent(System.out::println)
```

2021-06-04 06:20 UTC, ArtikTico approved these changes
Апруваю, но про то что в методе не пишется The не забывай

2021-06-04 06:20 UTC, ArtikTico commented on JiS7.iml
> +    </orderEntry>
ВЫнеси файл в гитигнор

2021-06-04 06:20 UTC, ArtikTico commented on src/main/java/LECTURE_Stream_API_And_Lambdas/Task3_Product3/Demo.java
> +        List<Product> minPriceInTheCollectionWithTheMaxDiscount = listProduct.stream()
Тут с Денисом соглашусь в названиях метода The не пишется

2021-06-04 06:20 UTC, ArtikTico commented on src/main/java/LECTURE_Stream_API_And_Lambdas/Task3_Product3/Demo.java
> +        System.out.println(minPriceInTheCollectionWithTheMaxDiscount);
А решение вполне себе норм.

2021-06-04 06:20 UTC, merged