Stream api task 4 part 1
BulavaKatsyaryna/JiS7 pull request #36
Opened 2021-05-28 22:27 UTC by BulavaKatsyaryna

2021-05-29 10:07 UTC, KaydunovDenis requested changes

2021-05-29 10:07 UTC, KaydunovDenis commented on src/main/java/LECTURE_Stream_API_And_Lambdas/Task4Part1/Demo.java
> +
empty lines

2021-05-29 10:07 UTC, KaydunovDenis commented on src/main/java/LECTURE_Stream_API_And_Lambdas/Task4Part1/Demo.java
> +                        Comparator.comparingDouble(Product::getPrice)
28 строчку перенести нужно на 27 строку

2021-05-29 10:07 UTC, KaydunovDenis commented on src/main/java/LECTURE_Stream_API_And_Lambdas/Task4Part1/Product.java
> +
empty line

2021-06-04 06:25 UTC, ArtikTico reviewed
Кать каждый раз после того как ты написала код, будь то метод, класс или переменная выделяй иногда весь код и нажимай Ctrl+Alt+ L чтобы форматировать по конвенции код.

2021-06-04 06:25 UTC, ArtikTico commented on Bulova.iml
> +</module>
гит игнор

2021-06-19 21:39 UTC, merged